# data-retrieval-deployment.yaml
# Deploy only once, so we use a Job instead of a Deployment
# Run only once, so we use restartPolicy: Never

apiVersion: batch/v1
kind: Job
metadata:
  name: data-retrieval-job
spec:
  template:
    metadata:
      labels:
        app: data-retrieval-pod
    spec:
      nodeSelector:
        role: "infra"  # Ensure the pod runs only on control-plane node
      containers:
      - name: data-retrieval
        image: cristhianron/data-retrival:1.0.0  # Replace with your Docker image name
        imagePullPolicy: Always        # Force the pull of the container image - used for testing purposes
        env:
        - name: REDIS_HOST
          value: "redis" # To be Filled
        - name: AWS_ACCESS_KEY_ID
          # Fill in with the Secret key value
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          # Fill in with the Secret key value
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
      restartPolicy: Never

# There is no service for this Job, because the job does not need to be accessed externally or expose any ports. 
# It will connect to the Redis service internally within the cluster. 
# The Redis service itself still needs a service definition to allow other pods to connect to it.

