# redis-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      # fill in the correct label
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      nodeSelector:
        role: infra  # Ensure Redis runs on infra nodes
      containers:
      - name: redis
        image: redislabs/redistimeseries:latest  # Use the RedisTimeSeries image
        ports:
        - containerPort: 6379
    
---
# redis-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    # Fill with the correct label
      app: redis-pod
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

